services:
  fta-backend:
    build: 
      context: ./fta_backend
      dockerfile: Dockerfile
    volumes:
      - ./fta_backend/:/app
    env_file:
      - .env
    ports:
      - ${FTA_BACKEND_PORT}:8000

  fta-db:
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

volumes:
  db_data: