# Generated by Django 5.1.2 on 2025-02-22 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['status'], name='fta_transac_status_51abce_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['merchant'], name='fta_transac_merchan_7a23f1_idx'),
        ),
    ]
