# Generated by Django 5.1.2 on 2025-03-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fta', '0002_transactionmodel_fta_transac_status_51abce_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-timestamp']},
        ),
    ]
